### ISSUE TITLE
Does not build on Varnish 4.0.0-tp1

### ISSUE THREAD

**Issue by gdlx** [TheWeatherChannel/dClass#10]
Hi,

dClass does not build on Varnish 4.0.0-tp1.

The first cause is `/lib/libvmod_std/vmod.py` being moved in `/lib/libvcc/vmodtool.py`, this is easily fixed.

But even after that, I'm getting this error:

```
gcc -O3 -Wall -fPIC -I/root/rpmbuild/SOURCES/varnish-4.0.0-tp1/include -I/root/rpmbuild/SOURCES/varnish-4.0.0-tp1 -I../../src -c vcc_if.c -o vcc_if.o
vcc_if.c:7:20: fatal error: config.h: No such file or directory
 #include "config.h"
                    ^
compilation terminated.
make: *** [vcc_if.o] Error 1
```

Are there some other little changes we can do to build dClass on Varnish 4 or is it totally incompatible ?

Thanks !
